# **NumPy Attributes and Operations**

NumPy is a popular Python library for numerical and scientific computing. It provides a wide range of functionality for working with arrays and matrices. NumPy arrays are at the core of the library, and they come with a variety of attributes and methods for performing operations

## **Array Attributes**



In [2]:
import numpy as np

In [3]:
# lets assume three array
a1 = np.arange(10,dtype=np.int32)

a2 = np.arange(12,dtype=float).reshape(3,4)

a3 = np.arange(8).reshape(2,2,2)

print(a1)
print('----------')
print(a2)
print('----------')
print(a3)

[0 1 2 3 4 5 6 7 8 9]
----------
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
----------
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


### **ndim**

This attribute returns the number of dimensions of a NumPy array. For example:

In [4]:
a1.ndim

1

In [5]:
a2.ndim

2

In [6]:
a3.ndim

3

* a1.ndim returns 1 because a1 is a one-dimensional array.
* a2.ndim returns 2 because a2 is a two-dimensional array.
* a3.ndim returns 3 because a3 is a three-dimensional array.

### **shape**

The shape attribute returns a tuple representing the dimensions of the array. For example:

In [7]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


* a1.shape returns (10,) because a1 is a one-dimensional array with a length of 10.
* a2.shape returns (3, 4) because a2 is a two-dimensional array with 3 rows and 4 columns.
* a3.shape returns (2, 2, 2) because a3 is a three-dimensional array with dimensions 2x2x2.

### **size**
The size attribute returns the total number of elements in the array. For example:

In [8]:
print(a1.size)
print(a2.size)
print(a3.size)
a3

10
12
8


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

* a1.size returns 10 because a1 has 10 elements.
* a2.size returns 12 because a2 has 12 elements.
* a3.size returns 8 because a3 has 8 elements.

### **itemsize**

The itemsize attribute returns the size (in bytes) of each element in the array. For example:

In [9]:
a2.itemsize

8

In [10]:
a3.itemsize

4

* a2.itemsize returns 8 because a2 is of type float64, which has 8 bytes per element.
* a3.itemsize returns 4 because a3 is of type int32, which has 4 bytes per element.

### **dtype**
The dtype attribute returns the data type of the elements in the array. For example:

In [11]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


* a1.dtype returns int32 because a1 is of type int32.
* a2.dtype returns float64 because a2 is of type float64.
* a3.dtype returns int32 because a3 is of type int32.

### **Changing Datatype**
You can change the data type of an array using the astype method. 

In [23]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

## **Array operations**

In [13]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [14]:
print(a1)
print('--------')
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


### **Scalar operations**

These operations involve performing mathematical operations on the entire array with a scalar value..

In [17]:
# arithmatic - all arithmatic opearation works like
print(a1 + 2)
print('-----')
print(a1 **2)
print('-----')
print(a1 - 5)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
-----
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
-----
[[-5 -4 -3 -2]
 [-1  0  1  2]
 [ 3  4  5  6]]


In [18]:
# relational -> all relational opearators work like
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [21]:
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### **vector operations**
These operations involve performing mathematical operations between two arrays.

In [22]:
# arithmetic
a1 ** a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

NumPy provides powerful tools for working with arrays efficiently, making it a valuable library for scientific and numerical computations in Python.