# **NumPy Fundamentals (Part-1)**

NumPy, which stands for "Numerical Python," is a fundamental Python library for scientific and numerical computing. It provides support for arrays (including multi-dimensional arrays) and a wide range of mathematical functions to operate on these arrays. NumPy is a crucial library in the Python scientific computing ecosystem and is often used in conjunction with other libraries like SciPy, Matplotlib, and pandas for various data analysis and scientific computing tasks.

NumPy is an essential tool for data scientists, engineers, and researchers working on numerical and scientific computing tasks in Python due to its efficiency, flexibility, and extensive mathematical capabilities.

Here are some key features and aspects of NumPy:

1. Arrays: NumPy's primary data structure is the ndarray (n-dimensional array). These arrays are similar to Python lists but are more efficient for numerical operations because they allow you to perform element-wise operations and take advantage of low-level optimizations.

2. Efficiency: NumPy is implemented in C and Fortran, making it highly efficient for numerical computations. It also provides tools to interface with libraries written in these languages.

3. Mathematical Functions: NumPy includes a wide range of mathematical functions for performing operations on arrays, such as addition, subtraction, multiplication, division, and more advanced operations like matrix multiplication, Fourier transforms, and linear algebra operations.

4. Broadcasting: NumPy allows you to perform operations on arrays of different shapes and sizes through a feature called broadcasting, which automatically aligns dimensions and performs operations element-wise.

5. Random Number Generation: NumPy provides functions for generating random numbers and random data, which is useful for tasks like simulations and statistical analysis.

6. Integration with Other Libraries: NumPy is often used in conjunction with libraries like SciPy for scientific computing, Matplotlib for data visualization, and pandas for data manipulation and analysis.

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### **How To Create NumPy Arrays**

1. **np.array**:
   - `np.array` is used to create NumPy arrays, which can be one-dimensional, two-dimensional, or multi-dimensional.
   - You need to import NumPy with `import numpy as np` before using it.
   - You can create arrays from Python lists or nested lists.

In [1]:
# np.array

import numpy as np  # we have to first import the numpy

a = np.array([1,2,3])
print(a)

[1 2 3]


2. **2D and 3D Arrays**:
   - NumPy allows you to create multi-dimensional arrays. You demonstrated 2D and 3D arrays using nested lists.

In [2]:
# 2D
n = np.array([[1,2,3],[4,5,6]])
print(n)

[[1 2 3]
 [4 5 6]]


In [3]:
# 3d
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


3. **dtype**:
   - You can specify the data type of the elements in a NumPy array using the `dtype` parameter.
   - In your example, you created arrays with `dtype=float` and `dtype=int` to explicitly set the data type.

In [4]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [5]:
np.array([1,2,3],dtype=int)

array([1, 2, 3])

4. **np.arange**:
   - `np.arange` is used to create a range of values within a specified interval.
   - It generates an array of evenly spaced values, similar to Python's `range` function.

In [6]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

5. **Reshaping Arrays**:
   - You can reshape an array using the `reshape` method. This changes the dimensions of the array while maintaining the total number of elements.
   - In your example, you used `reshape` to create a 4D array from a 1D array.

In [7]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

6. **np.ones**:
   - `np.ones` creates an array filled with ones.
   - You specify the shape of the array as a tuple. For example, `np.ones((3,4))` creates a 3x4 array filled with ones.

In [8]:
# np.ones 
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

7. **np.zeros**:
   - `np.zeros` creates an array filled with zeros.
   - Similar to `np.ones`, you specify the shape of the array as a tuple.

In [9]:
#np.zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

8. **np.random**:
   - `np.random.random` generates random numbers between 0 and 1 in a specified shape.
   - It's useful for generating random data for simulations or experiments.

In [10]:
# np.random
np.random.random((3,4))

array([[0.56431434, 0.09281216, 0.52283734, 0.34159087],
       [0.3840281 , 0.07649243, 0.09074241, 0.4599812 ],
       [0.09965102, 0.6279051 , 0.54948164, 0.29137218]])

9. **np.linspace**:
   - `np.linspace` generates evenly spaced values over a specified range.
   - You specify the start, end, and the number of values you want. In your example, you used `dtype=int` to ensure integer values.

In [11]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

10. **np.identity**:
    - `np.identity` creates an identity matrix, which is a square matrix with ones on the diagonal and zeros elsewhere.
    - You specify the size of the identity matrix as a single integer.

In [12]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

These NumPy functions are essential tools for working with numerical data in Python. They provide the foundation for many scientific and data analysis tasks, making it easier to perform calculations and manipulate data efficiently.