# **NumPy Fundamentals(part-2)**

In [1]:
import numpy as np

## **Part 1 - Creating Arrays:**
- `a1`, `a2`, and `a3` are NumPy arrays of different dimensions created using `np.arange` and `reshape`.
- `a1` is a 1D array with 10 elements.
- `a2` is a 2D array with a shape of (3, 4).
- `a3` is a 3D array with a shape of (2, 2, 2).

In [2]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print('-------------')
print(a2)
print('-------------')
print(a3)

[0 1 2 3 4 5 6 7 8 9]
-------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


## **Part 2 - Indexing and Slicing:**
- Demonstrates how to access elements in NumPy arrays.
- For a 1D array (`a1`), elements are accessed by their index.
- For a 2D array (`a2`), elements are accessed using row and column indices.
- Slicing is shown for both 1D and 2D arrays, allowing you to extract specific ranges of elements.


In [3]:
# For 1D array
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# how to extract 5 from a1?
print(a1[5])

# how to extract 8 from a1?
print(a1[6])

5
6


In [8]:
# how to extract 3 to 8 from a1?
print(a1[3:9])

[3 4 5 6 7 8]


In [9]:
# for 2D array
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
# how to extract 4 from a2

print(a2[1,0])

# How to extract 11 from a2

print(a2[2,3])


4
11


In [13]:
# how to extract 1-2, 9-11 from a2
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [14]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [15]:
a2[1,::3]

array([4, 7])

In [17]:
# For 3D Array
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [21]:
# how to extract 18
a3[2,0,0]

18

In [25]:
# how to extract 19 and 20
a3[2,0,1:]

array([19, 20])

In [18]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [19]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [20]:
a3[0,1,:]

array([3, 4, 5])

## **Part 3 - Iterating:**
- Iterating through NumPy arrays using `for` loops.
- Shows how to loop through elements in 1D and 2D arrays.
- The `np.nditer` function is introduced for iterating through all elements in the array.

In [27]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [30]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [34]:
for i in np.nditer(a2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [31]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [32]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [33]:
# nditer
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## **Part 4 - Reshaping:**
- Reshaping NumPy arrays using `np.reshape`.
- Reshaping is demonstrated on a 2D array (`a2`), changing its shape from (3, 4) to (4, 3).
- The `np.transpose` function is used to obtain the transpose of the array, effectively swapping rows and columns.

In [38]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Reshape

In [39]:
np.reshape(a2,(4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### Transpose

In [42]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [41]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## **Part 5 - Ravel and Stacking:**
- The `ravel` method is used to flatten a multi-dimensional array into a 1D array.
- Stacking arrays horizontally (`hstack`) and vertically (`vstack`) is demonstrated.
- Horizontal stacking combines arrays side by side, while vertical stacking stacks arrays on top of each other.

## **raval**

In [44]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## **Stacking**

In [45]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [47]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])