# **NumPy - Array Functions**

In [10]:
import numpy as np

### 1. **Creating NumPy Arrays:**
   - You can create NumPy arrays using `np.random.random()`, `np.arange()`, and reshaping methods like `reshape()`. In your example, you created three NumPy arrays, `a1`, `a2`, and `a3`.

In [11]:
# first we have to assume three numpy arrays
a1 = np.random.random((3,3))
a1 = np.round(a1*100)

a2 = np.arange(12).reshape(3,4)

a3 = np.arange(12,24).reshape(4,3)

print(a1)
print('------------')
print(a2)
print('-------------')
print(a3)

[[74. 98. 34.]
 [89. 62. 11.]
 [29. 87. 44.]]
------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


### 2. **Maximum, Minimum, Sum, and Product:**
   - You can find the maximum value in an array using `np.max()`.
   - You can find the minimum value in an array using `np.min()`.
   - You can calculate the sum of all elements in an array using `np.sum()`.
   - You can calculate the product of all elements in an array using `np.prod()`.
   - By specifying the `axis` parameter, you can find the maximum or minimum along columns (axis=0) or rows (axis=1).

In [12]:
np.max(a1)

98.0

In [13]:
np.min(a1)

11.0

In [14]:
np.sum(a1)

528.0

In [15]:
np.prod(a1)

1661426069717568.0

In [16]:
# if we want seperate for columns and rows
# axis -> 0 = columns , 1 = row

np.max(a1,axis=0)

array([89., 98., 44.])

In [17]:
np.max(a1,axis=1)

array([98., 89., 87.])

In [18]:
np.min(a1,axis=0)

array([29., 62., 11.])

### 3. **Mean, Median, Standard Deviation, and Variance:**
   - You can calculate the mean of an array using `np.mean()`.
   - You can find the median value in an array using `np.median()`.
   - You can calculate the standard deviation of an array using `np.std()`.
   - You can compute the variance of an array using `np.var()`.
   - Similar to the previous case, you can specify the `axis` parameter for calculations along columns or rows.


In [19]:
np.mean(a1)

58.666666666666664

In [20]:
np.median(a2)

5.5

In [21]:
np.std(a1)

28.85211334450987

In [22]:
np.var(a1)

832.4444444444446

In [23]:
# for columns and rows
np.median(a1,axis=1)

array([74., 62., 44.])

In [24]:
np.median(a1,axis=0)

array([74., 87., 34.])

### 4. **Trigonometric Functions:**
   - You can apply trigonometric functions to an array, such as sine (`np.sin()`) and cosine (`np.cos()`), which perform element-wise calculations on the input array.

In [25]:
np.sin(a1)

array([[-0.98514626, -0.57338187,  0.52908269],
       [ 0.86006941, -0.7391807 , -0.99999021],
       [-0.66363388, -0.82181784,  0.01770193]])

In [26]:
np.cos(a1)

array([[ 0.17171734, -0.81928825, -0.84857027],
       [ 0.51017704,  0.67350716,  0.0044257 ],
       [-0.74805753,  0.56975033,  0.99984331]])

### 5. **Dot Product:**
   - The `np.dot()` function computes the dot product of two arrays, which is particularly useful for matrix multiplication. In your example, you multiplied `a2` and `a3` using `np.dot()` to obtain the result.

In [28]:
print(a2)

print('------------')

print(a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
------------
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [29]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

### 6. **Logarithms and Exponents:**
   - You can compute the natural logarithm of an array using `np.log()`.
   - You can calculate the exponential of each element in an array using `np.exp()`.

In [30]:
np.log(a1)

array([[4.30406509, 4.58496748, 3.52636052],
       [4.48863637, 4.12713439, 2.39789527],
       [3.36729583, 4.46590812, 3.78418963]])

In [31]:
np.exp(a1)

array([[1.37338298e+32, 3.63797095e+42, 5.83461743e+14],
       [4.48961282e+38, 8.43835667e+26, 5.98741417e+04],
       [3.93133430e+12, 6.07603023e+37, 1.28516001e+19]])

### 7. **Rounding, Flooring, and Ceiling:**
   - You can round the elements of an array to the nearest integer using `np.round()`.
   - You can round down the elements to the nearest integer using `np.floor()`.
   - You can round up the elements to the nearest integer using `np.ceil()`.


In [42]:
a=np.random.random((2,3))*100
print(a)

[[12.34714055 34.11903111 28.73639357]
 [97.69723411 52.68276927 61.09195526]]


In [43]:
np.round(a)

array([[12., 34., 29.],
       [98., 53., 61.]])

In [44]:
np.floor(a)

array([[12., 34., 28.],
       [97., 52., 61.]])

In [45]:
np.ceil(a)

array([[13., 35., 29.],
       [98., 53., 62.]])

These NumPy functions and operations are essential tools for numerical and scientific computing in Python, providing a wide range of capabilities for data manipulation, analysis, and mathematical calculations.

Check Out this for more NumPy Functions - https://numpy.org/doc/stable/reference/routines.math.html