# **NumPy Interview Questions(part-2)**

### `1. Explain the use of NumPy's random module for generating random Numbers`

NumPy's `random` module provides a suite of functions for generating random numbers, which is useful for various applications such as simulations, statistical modeling, and machine learning. The `random` module is a sub-module of NumPy, and it offers a wide range of functions to generate random numbers with different distributions.

Here are some key functions and concepts related to NumPy's `random` module:

### 1. **Simple Random Data:**
   - NumPy provides functions to generate arrays of random data with a uniform distribution.





   







In [1]:
import numpy as np

# Generate random floats in the half-open interval [0.0, 1.0)
random_numbers = np.random.random(size=5)
random_numbers

array([0.11442764, 0.70706516, 0.17581463, 0.12075097, 0.19547172])

### 2. **Random Integers:**
   - You can generate random integers within a specified range.


In [3]:
# Generate random integers in the half-open interval [low, high)
random_integers = np.random.randint(low=1, high=10, size=5)
random_integers

array([1, 5, 6, 8, 7])

### 3. **Random Sampling:**
   - Functions like `choice` allow you to sample from a given array.


In [5]:
# Randomly sample from a given array
choices = np.random.choice(['a', 'b', 'c'], size=5)
choices

array(['a', 'b', 'a', 'c', 'c'], dtype='<U1')

### 4. **Permutations:**
   - NumPy can be used to generate random permutations.

In [7]:
# Randomly permute a sequence
permutation = np.random.permutation([1, 2, 3, 4, 5])
permutation

array([3, 4, 1, 5, 2])

### 5. **Distributions:**
   - NumPy's `random` module supports various probability distributions such as normal, binomial, exponential, etc.

In [9]:
# Generate random numbers from a normal distribution
normal_distribution = np.random.normal(loc=0, scale=1, size=5)
normal_distribution

array([ 0.96949722,  0.27283578, -0.27559331, -0.5644573 , -0.36100325])

These functions provide flexibility in generating random data according to different needs, and they are crucial tools for various statistical and numerical simulations. The ability to set a seed is especially useful when reproducibility is important, allowing you to recreate the same set of random numbers for debugging or sharing code with others.


### `2. How can you find the maximum and minimum values in a NumPy Array?`  


In NumPy, you can find the maximum and minimum values in an array using the `np.max()` and `np.min()` functions, respectively. These functions offer flexibility in finding the maximum and minimum values across different axes or the entire array.

Here are the basic usages:

###  Finding the Maximum and Minimum in the Entire Array:


In [1]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 5, 3, 8, 2])

# Find the maximum and minimum values
max_value = np.max(arr)
min_value = np.min(arr)

print("Maximum Value:", max_value)
print("Minimum Value:", min_value)

Maximum Value: 8
Minimum Value: 1


### `3.How do you convert Pandas DataFrame to a NumPy array?`

The to_numpy() method of the NumPy package can be used to convert Pandas DataFrame, Index and Series objects.

Consider we have a DataFrame df, we can either convert the whole Pandas DataFrame df to NumPy array or even select a subset of Pandas DataFrame to NumPy array by using the to_numpy() method as shown in the example below:

In [2]:
import pandas as pd
import numpy as np
# Pandas DataFrame
df = pd.DataFrame(data={'A': [3, 2, 1], 'B': [6,5,4], 'C': [9, 8, 7]}, 
                  index=['i', 'j', 'k'])
print("Pandas DataFrame: ")
print(df)

# Convert Pandas DataFrame to NumPy Array
np_arr = df.to_numpy()
print("Pandas DataFrame to NumPy array: ")
print(np_arr)


# Convert specific columns of Pandas DataFrame to NumPy array
arr = df[['B', 'C']].to_numpy()
print("Convert B and C columns of Pandas DataFrame to NumPy Array: ")
print (arr)

Pandas DataFrame: 
   A  B  C
i  3  6  9
j  2  5  8
k  1  4  7
Pandas DataFrame to NumPy array: 
[[3 6 9]
 [2 5 8]
 [1 4 7]]
Convert B and C columns of Pandas DataFrame to NumPy Array: 
[[6 9]
 [5 8]
 [4 7]]


### `4.How is vstack() different from hstack() in NumPy?`

Both methods are used for combining the NumPy arrays. The main difference is that the hstack method combines arrays horizontally whereas the vstack method combines arrays vertically.
For example, consider the below code.

In [3]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

# vstack arrays
c = np.vstack((a,b))
print("After vstack: \n",c)
# hstack arrays
d = np.hstack((a,b))
print("After hstack: \n",d)

After vstack: 
 [[1 2 3]
 [4 5 6]]
After hstack: 
 [1 2 3 4 5 6]


### `5. Write a program for creating an integer array with values belonging to the range 10 and 60`


In [4]:
import numpy as np
arr = np.arange(10, 60)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59]
