# **NumPy Interview Questions**

### `1. What is NumPy, and how is it different from Python List?`

NumPy is a powerful numerical computing library in Python. It provides support for large, multi-dimensional arrays and matrices, along with mathematical functions to operate on these arrays. NumPy is a fundamental package for scientific computing in Python, and many other libraries, such as pandas and scikit-learn, are built on top of it.

Here are some key differences between NumPy arrays and Python lists:

1. **Homogeneity:**
   - NumPy arrays are homogeneous, meaning that all elements of an array must be of the same data type. This allows for more efficient storage and computation.
   - Python lists can contain elements of different data types.

2. **Size:**
   - NumPy arrays are more compact in memory compared to Python lists. This is because NumPy arrays are implemented in C and allow for more efficient storage of data.
   - Python lists have more overhead and are generally less memory-efficient.

3. **Performance:**
   - NumPy operations are implemented in C, which makes them much faster than equivalent operations on Python lists, especially for large datasets.
   - NumPy provides a wide range of efficient functions for array operations, such as element-wise operations, linear algebra, and statistical operations.

4. **Functionality:**
   - NumPy provides a variety of functions for performing operations on arrays, such as element-wise operations, linear algebra, statistical operations, and more.
   - While Python lists have some built-in functions, NumPy provides a more extensive set of tools specifically designed for numerical operations.

5. **Syntax:**
   - NumPy arrays support vectorized operations, which means that operations can be performed on entire arrays without the need for explicit loops. This leads to more concise and readable code.
   - In Python lists, you often need to use explicit loops for element-wise operations.

Here's a simple example to illustrate the differences:



In [10]:
# Using Python lists
python_list1 = [1, 2, 3]
python_list2 = [4, 5, 6]
sum_python_lists = python_list1 + python_list2  # Concatenation, not element-wise addition
print('Sum_Python_list -',sum_python_lists)

# Using NumPy arrays
import numpy as np

numpy_array1 = np.array([1, 2, 3])
numpy_array2 = np.array([4, 5, 6])
sum_numpy_arrays = numpy_array1 + numpy_array2  # Element-wise addition
print('Numpy_list_sum -',sum_numpy_arrays)

Sum_Python_list - [1, 2, 3, 4, 5, 6]
Numpy_list_sum - [5 7 9]


In the NumPy example, the addition is performed element-wise, which is a fundamental concept in numerical computing. In contrast, the Python list example concatenates the two lists without performing element-wise addition.

### `2.Explain the concept of Broadcasting in NumPy?`

Broadcasting is a powerful feature in NumPy that allows you to perform operations on arrays of different shapes and sizes. The term "broadcasting" refers to how NumPy treats arrays with different shapes during arithmetic operations. The smaller array is "broadcast" across the larger array so that they have compatible shapes.

The broadcasting rule in NumPy is as follows:

1. If the arrays do not have the same rank (number of dimensions), pad the smaller shape with ones on its left side.

2. Compare the sizes of the corresponding dimensions:
   - If the sizes of the dimensions are different, but one of them is 1, then the arrays are compatible for broadcasting.
   - If the sizes in a dimension are neither equal nor one, broadcasting is not possible, and a `ValueError` is raised.

3. After the broadcasting, each array behaves as if its shape was the element-wise maximum of both shapes.

Let's go through a simple example to illustrate broadcasting:




In [12]:
import numpy as np

# Example 1: Broadcasting a scalar to an array
scalar_value = 5
array = np.array([1, 2, 3])
result = scalar_value + array
# The scalar is broadcasted to the shape of the array, resulting in [6, 7, 8]
result

array([6, 7, 8])

In [13]:
# Example 2: Broadcasting a 1D array to a 2D array
array_1d = np.array([1, 2, 3])
array_2d = np.array([[4, 5, 6], [7, 8, 9]])
result = array_1d + array_2d
# The 1D array is broadcasted along the second dimension of the 2D array,
# resulting in [[5, 7, 9], [8, 10, 12]]
result

array([[ 5,  7,  9],
       [ 8, 10, 12]])

In [14]:
# Example 3: Broadcasting both arrays
array_a = np.array([[1], [2], [3]])
array_b = np.array([4, 5, 6])
result = array_a + array_b
# Both arrays are broadcasted, resulting in [[5, 6, 7], [6, 7, 8], [7, 8, 9]]
result

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In these examples, the smaller array or scalar is broadcasted to match the shape of the larger array, and the element-wise operation is then performed. This broadcasting mechanism allows for more concise and readable code when working with arrays of different shapes, making NumPy operations more flexible.

### `3.How do you perform Element wise addition of two NumPy arrays?`

Performing element-wise addition of two NumPy arrays is straightforward. You can use the + operator, and NumPy will handle the element-wise addition automatically. Here's an example:

In [15]:
import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Perform element-wise addition
result_array = array1 + array2

# Display the result
print(result_array)


[5 7 9]


In this example, array1 + array2 performs element-wise addition, resulting in a new NumPy array [5, 7, 9]. NumPy takes care of broadcasting if the arrays have different shapes but are still compatible according to the broadcasting rules.

You can perform element-wise addition, subtraction, multiplication, and division using the standard arithmetic operators (+, -, *, /). NumPy will apply these operations element-wise to the corresponding elements of the arrays.

In [16]:
import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Element-wise operations
result_addition = array1 + array2  # Element-wise addition
result_subtraction = array1 - array2  # Element-wise subtraction
result_multiplication = array1 * array2  # Element-wise multiplication
result_division = array1 / array2  # Element-wise division

# Display the results
print("Addition:", result_addition)
print("Subtraction:", result_subtraction)
print("Multiplication:", result_multiplication)
print("Division:", result_division)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


### `4.What is the purpose of the np.mean() function in NumPy?`

The np.mean() function in NumPy is used to compute the arithmetic mean, or average, of elements along a specified axis or of the entire array. The mean is calculated by summing up all the elements and dividing the sum by the total number of elements.

In [17]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Calculate the mean of the array
mean_value = np.mean(arr)

print("Mean:", mean_value)


Mean: 3.0


In this example, np.mean(arr) will calculate the mean of the elements [1, 2, 3, 4, 5], which is (1 + 2 + 3 + 4 + 5) / 5 = 3.0.

### `5. How do you reshape a NumPy Arrays?`

You can reshape a NumPy array using the reshape() function. Reshaping means changing the shape (dimensions) of the array while keeping the total number of elements the same. The reshape() function takes the desired shape as an argument.

In [18]:
import numpy as np

# Create a NumPy array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to a 2x3 matrix
reshaped_array = original_array.reshape(2, 3)

print("Original array:")
print(original_array)

print("\nReshaped array:")
print(reshaped_array)


Original array:
[1 2 3 4 5 6]

Reshaped array:
[[1 2 3]
 [4 5 6]]


In this example, original_array is reshaped into a 2x3 matrix using reshape(2, 3). 